import Head from 'next/head';
import Image from 'next/image';
import Header from '../../components/Header';
import Background from '../../public/Background.jpg';
import { db } from '../../config/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { useState } from 'react';

export default function Home() {
  const [hospital, setHospital] = useState('');
  const [patient, setPatient] = useState('');
  const [number, setNumber] = useState('');
  const [date, setDate] = useState('');

  const database = collection(db, 'users');

  const handleClick = () => {
    addDoc(database, {
      hospitalName: hospital,
      patientName: patient,
      phoneNumber: number,
      date: date,
      time: serverTimestamp(),
    })
      .then(() => {
        setHospital('');
        setPatient('');
        setNumber('');
        setDate('');
      })
      .catch((err) => {
        console.error(err);
      });
  };

  return (
    <>
      <Head>
        <title>Balansame</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <div>
          <div className="pt-32 pb-24 w-10/12 flex flex-col justify-center m-auto">
            <h1 className=" text-white leading-12 text-center base text-3xl font-bold underline">
              Halkan Ka Balanso Dhakhtar <br /> Ka Aad U Baahan Tahay
            </h1>

            <div className="flex flex-col justify-center mx-auto ">
              <p className="font-body text-xs  md:w-[50%] mx-auto font-medium pt-10 text-center leading-6 text-[#A0A0A0]">
                Established on June 2014, Rays Microfinance Institution S.C. was
                an inception of few individuals that had a deep-rooted desire to
                contribute to and play a role towards mitigating the
                vulnerability.
              </p>
            </div>

            <div className="bg-[#2A3A8A]/50 backdrop-blur-sm mt-32 rounded-2xl">
              <div className="p-6 m-auto text-center ">
                <input
                  onChange={(e) => setHospital(e.target.value)}
                  value={hospital}
                  type="search"
                  placeholder="Select Hospital"
                  className="bg-[#85ABF3]/30 text-white px-3 py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setPatient(e.target.value)}
                  value={patient}
                  placeholder="Patient Name"
                  className="bg-[#85ABF3]/30 px-3 text-white py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setNumber(e.target.value)}
                  value={number}
                  placeholder="Phone Number"
                  className="bg-[#85ABF3]/30 px-3 text-white py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setDate(e.target.value)}
                  value={date}
                  type="date"
                  className="bg-[#85ABF3]/30  text-white px-3 py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full "
                />

                <button
                  onClick={handleClick}
                  className="px-8 py-4 mb-3 mr-3 max-[700px]:w-full rounded-xl bg-[#6379E5] text-white"
                >
                  Submit
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
