import Head from 'next/head';
import Image from 'next/image';
import Header from '../../components/Header';
import Background from '../../public/Background.jpg';
import BloodBag from '../../public/bloodbag.png';

export default function Home() {
  return (
    <>
      <Head>
        <title>BloodBank</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[url('../../public/BG.jpg')] bg-cover h-screen">
        <Header />
        <div className="flex justify-center max-[1080px]:flex-wrap max-[1080px]:text-center  mx-auto items-center w-10/12 ">
          <div className="pt-32 pb-24  flex flex-col mx-auto">
            <h1 className=" text-white leading-12 base text-5xl font-bold underline">
              Ku Deeq Dhiig Oo <br /> Bad Baadi Naf
            </h1>

            <p className="font-body text-xs max-[1080px]:mx-auto  md:w-[50%]  font-medium pt-10 leading-6 text-[#A0A0A0]">
              is simply dummy text of the printing and typesetting industry.
              Lorem Ipsum has been the industry's standard dummy text ever since
              the 1500s, when an unknown printer took a galley of type and
              scrambled it to make a type specimen book.
            </p>

            {/* <div className="bg-[#2A3A8A]/50 backdrop-blur-sm mt-32 rounded-2xl">
              <div className="p-6 m-auto text-center ">
                <input
                  onChange={(e) => setHospital(e.target.value)}
                  value={hospital}
                  type="search"
                  placeholder="Select Hospital"
                  className="bg-[#85ABF3]/30 text-white px-3 py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setPatient(e.target.value)}
                  value={patient}
                  placeholder="Patient Name"
                  className="bg-[#85ABF3]/30 px-3 text-white py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setNumber(e.target.value)}
                  value={number}
                  placeholder="Phone Number"
                  className="bg-[#85ABF3]/30 px-3 text-white py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full"
                />

                <input
                  onChange={(e) => setDate(e.target.value)}
                  value={date}
                  type="date"
                  className="bg-[#85ABF3]/30  text-white px-3 py-4 rounded-xl mb-3 mr-3 max-[700px]:w-full "
                />

                <button
                  onClick={handleClick}
                  className="px-8 py-4 mb-3 mr-3 max-[700px]:w-full rounded-xl bg-[#6379E5] text-white"
                >
                  Submit
                </button>
              </div>
            </div> */}
          </div>
          <Image src={BloodBag} alt="bloodbag" width={480} height={'auto'} />
        </div>

        <div className="flex w-10/12 justify-between mx-auto text-xs  max-[1080px]:pt-8 max-[1080px]:pb-12 font-semibold text-[#A0A0A0] underline mt-3 ">
          <p>
            www.hargeisablood.com <br /> Info.hargeisablood.com
          </p>

          <p>
            Jigjiga yar, Koodbuur <br /> Hargeisa, Somaliland
          </p>

          <p>
            252 67 906 985 98 <br /> 252 97 908 986 98
          </p>
        </div>
      </main>
    </>
  );
}
